### PR TITLE
Issue #18 hotfix

### PR DESCRIPTION
**Pull request by ejokeeffe**
Hot fix for #18 
- Added ability to add foreign key constraints to sql.py Table class
- Also added try/catch in aisdb.py (same principle as applied when adding indices) around adding the trigger as it was falling over when you update an existing database

### CODE REVIEW

**Comment by willu47** [comment]
@ejokeeffe, does this also fix #16?

**Comment by ejokeeffe** [comment]
No it doesn't fix #16 - I've left #16 open as I wasn't sure if there was a reason why they are being set in uppercase? I can't think of one but didn't want to assume.

**Comment by willu47** [comment]
Cool.  Well, I'm happy to merge this and bump the minor release.

**Comment by ejokeeffe** [comment]
great, thanks.

**Pull request merged**
